"""
Deterministic eligibility engine.

THIS MODULE MAKES THE ELIGIBILITY DECISION. No LLM is involved here.

The engine is pure, dependency-free (stdlib only), and fully traceable: every
decision it emits carries a `Citation` pointing back to the exact knowledge-base
entry that produced it. The LLM layer, added later, may only *explain* the
`EligibilityResult` this module returns — it must never override a decision.

Public entry point: `evaluate(profile) -> EligibilityResult`.
"""
from __future__ import annotations

from typing import Any

from .knowledge import get_activity, load_free_zones, load_ownership_rules
from .models import (
    BusinessProfile,
    Citation,
    CostBreakdown,
    EligibilityResult,
    Reason,
    SetupType,
    TargetMarket,
    VisaAssessment,
    ZoneRecommendation,
)

# Standard disclaimer attached to every result.
STANDARD_DISCLAIMERS = [
    "This is directional guidance generated by a rules engine, NOT legal, tax, or "
    "financial advice.",
    "All costs are approximate publicly-advertised bands for 2025/2026 and change "
    "frequently; confirm a live quote with the zone authority.",
    "Confirm your exact business activity code and its licensing rules with the "
    "relevant DED or free zone authority, or a licensed corporate services provider, "
    "before acting.",
]

# Cost-tier bonus: nudges cost-sensitive founders toward cheaper zones as a
# tie-breaker only; specialization match always dominates.
_COST_TIER_BONUS = {
    "very_low": 4.0,
    "low": 3.0,
    "medium": 1.0,
    "high": 0.0,
    "premium": -1.0,
}

_PRESTIGE_BONUS = {"high": 0.5, "medium": 0.25, "low": 0.0}

_SPECIALIZATION_WEIGHT = 10.0  # points per matching category — the dominant signal
_BUDGET_FIT_BONUS = 5.0
_BUDGET_OVER_PENALTY = 8.0
_EMIRATE_PREFERENCE_BONUS = 2.0

_MIN_OFFICE_SQM = 9  # a single dedicated desk/office floor


# --------------------------------------------------------------------------- #
# Citation helpers
# --------------------------------------------------------------------------- #
def _activity_citation(rule_id: str, activity: dict[str, Any]) -> Citation:
    return Citation(
        rule_id=rule_id,
        source_ref=f"activities.json#{activity['id']}",
        source=activity.get("source", "activities.json"),
    )


def _ownership_citation(rule_id: str, rule: dict[str, Any]) -> Citation:
    return Citation(
        rule_id=rule_id,
        source_ref=f"ownership_rules.json#{rule_id}",
        source=rule.get("source", "ownership_rules.json"),
    )


def _zone_citation(rule_id: str, zone: dict[str, Any]) -> Citation:
    return Citation(
        rule_id=rule_id,
        source_ref=f"free_zones.json#{zone['id']}",
        source=zone.get("source", "free_zones.json"),
    )


# --------------------------------------------------------------------------- #
# Step 1 — Mainland vs Free Zone
# --------------------------------------------------------------------------- #
def _decide_setup_type(
    profile: BusinessProfile, activity: dict[str, Any]
) -> tuple[SetupType, list[Reason]]:
    reasons: list[Reason] = []

    # Rule 1: some activities are simply not free-zone eligible for the onshore market.
    if activity.get("mainland_required"):
        reasons.append(
            Reason(
                text=(
                    f"“{activity['label']}” must be licensed on the mainland: "
                    f"{activity['notes']}"
                ),
                citation=_activity_citation("mainland_required_activity", activity),
            )
        )
        return SetupType.MAINLAND, reasons

    # Rule 2: if the primary market is the UAE onshore public, mainland gives direct
    # market access. A free zone company cannot invoice onshore customers directly.
    if profile.target_market == TargetMarket.LOCAL_UAE:
        reasons.append(
            Reason(
                text=(
                    "Your primary market is the UAE onshore market. A free zone company "
                    "cannot sell directly to onshore customers without a mainland "
                    "distributor or a dual licence, so a mainland licence is the cleaner "
                    "route for direct local-market access."
                ),
                citation=_activity_citation("local_market_favours_mainland", activity),
            )
        )
        return SetupType.MAINLAND, reasons

    # Rule 3: free-zone eligible + international / mixed focus → free zone.
    reasons.append(
        Reason(
            text=(
                f"“{activity['label']}” is free-zone eligible and your focus is "
                f"{'international' if profile.target_market == TargetMarket.INTERNATIONAL else 'international with some local'} "
                "business, which suits a free zone (100% ownership, lower cost, faster setup)."
            ),
            citation=_activity_citation("free_zone_eligible_activity", activity),
        )
    )
    if profile.target_market == TargetMarket.BOTH:
        reasons.append(
            Reason(
                text=(
                    "Because you also expect some UAE onshore sales, note that a free zone "
                    "company needs a local distributor or a dual/mainland licence to invoice "
                    "onshore customers directly."
                ),
                citation=_activity_citation("both_markets_need_distributor", activity),
            )
        )
    return SetupType.FREE_ZONE, reasons


# --------------------------------------------------------------------------- #
# Step 2 — Ownership assessment
# --------------------------------------------------------------------------- #
def _ownership_reasons(
    setup_type: SetupType, profile: BusinessProfile
) -> list[Reason]:
    rules = load_ownership_rules()
    reasons: list[Reason] = []

    if setup_type == SetupType.FREE_ZONE:
        rule = rules["free_zone_always_100_percent"]
        reasons.append(
            Reason(
                text="100% foreign ownership is guaranteed: " + rule["explanation"],
                citation=_ownership_citation("free_zone_always_100_percent", rule),
            )
        )
        return reasons

    # Mainland ownership.
    rule = rules["mainland_default_since_2021"]
    reasons.append(
        Reason(
            text="Foreign ownership on the mainland: " + rule["explanation"],
            citation=_ownership_citation("mainland_default_since_2021", rule),
        )
    )
    if profile.needs_100_percent_foreign_ownership:
        strategic = rules["strategic_activities_still_restricted"]
        reasons.append(
            Reason(
                text=(
                    "You require 100% ownership. This is available for most mainland "
                    "activities post-2021, but confirm your specific activity is not on the "
                    "residual strategic-activities list that still needs Emirati involvement."
                ),
                citation=_ownership_citation(
                    "strategic_activities_still_restricted", strategic
                ),
            )
        )
    return reasons


# --------------------------------------------------------------------------- #
# Step 3 — Visa assessment for a zone
# --------------------------------------------------------------------------- #
def _assess_visas(
    profile: BusinessProfile, zone: dict[str, Any]
) -> VisaAssessment:
    visa_rules = zone["visa_rules"]
    flexi_cap = int(visa_rules["flexi_desk_max_visas"])
    sqm_per_visa = int(visa_rules["sqm_per_visa"])
    requested = profile.employee_visa_count

    dedicated_office_required = (
        profile.physical_office_needed or requested > flexi_cap
    )
    flexi_sufficient = (not dedicated_office_required) and requested <= flexi_cap

    estimated_sqm: int | None = None
    if dedicated_office_required and requested > 0:
        estimated_sqm = max(_MIN_OFFICE_SQM, requested * sqm_per_visa)

    if flexi_sufficient:
        note = (
            f"{requested} visa(s) fit within this zone's flexi-desk allocation "
            f"(up to {flexi_cap}); no dedicated office is required. {visa_rules['notes']}"
        )
    elif requested > flexi_cap:
        note = (
            f"{requested} visa(s) exceed the flexi-desk cap of {flexi_cap}, so a dedicated "
            f"office of roughly {estimated_sqm} sqm (~{sqm_per_visa} sqm/visa) is needed. "
            f"{visa_rules['notes']}"
        )
    else:  # office explicitly requested
        note = (
            f"You asked for a physical office, so a dedicated space of roughly "
            f"{estimated_sqm} sqm supports your {requested} visa(s). {visa_rules['notes']}"
        )

    return VisaAssessment(
        requested_visas=requested,
        flexi_desk_sufficient=flexi_sufficient,
        dedicated_office_required=dedicated_office_required,
        estimated_office_sqm=estimated_sqm,
        notes=note,
        citation=_zone_citation("visa_quota_rule", zone),
    )


# --------------------------------------------------------------------------- #
# Step 4 — Cost breakdown for a zone
# --------------------------------------------------------------------------- #
def _cost_breakdown(
    profile: BusinessProfile, zone: dict[str, Any]
) -> CostBreakdown:
    setup = zone["setup_cost_aed"]
    renewal = zone["annual_renewal_aed"]
    per_visa = zone["per_visa_cost_aed"]
    n = profile.employee_visa_count

    setup_band = (int(setup["min"]), int(setup["max"]))
    renewal_band = (int(renewal["min"]), int(renewal["max"]))
    visa_band = (int(per_visa["min"]) * n, int(per_visa["max"]) * n)
    first_year = (setup_band[0] + visa_band[0], setup_band[1] + visa_band[1])

    return CostBreakdown(
        zone_id=zone["id"],
        setup_cost_aed=setup_band,
        annual_renewal_aed=renewal_band,
        visa_cost_aed=visa_band,
        first_year_total_aed=first_year,
        approximate=True,
        citation=_zone_citation("cost_bands", zone),
    )


# --------------------------------------------------------------------------- #
# Step 5 — Score and rank free zones
# --------------------------------------------------------------------------- #
def _score_zone(
    profile: BusinessProfile,
    activity: dict[str, Any],
    zone: dict[str, Any],
    cost: CostBreakdown,
) -> tuple[float, list[Reason], int]:
    """Return (score, match_reasons, overlap_count)."""
    reasons: list[Reason] = []
    activity_categories = set(activity.get("categories", []))
    zone_specializations = set(zone.get("specializations", []))
    overlap = sorted(activity_categories & zone_specializations)

    score = 0.0

    if overlap:
        score += _SPECIALIZATION_WEIGHT * len(overlap)
        reasons.append(
            Reason(
                text=(
                    f"{zone['name']} specializes in {', '.join(overlap)}, matching your "
                    f"activity profile."
                ),
                citation=_zone_citation("specialization_match", zone),
            )
        )

    # Cost tier bonus (tie-breaker toward affordability).
    score += _COST_TIER_BONUS.get(zone.get("cost_tier", "medium"), 1.0)

    # Prestige tie-breaker.
    score += _PRESTIGE_BONUS.get(zone.get("prestige", "low"), 0.0)

    # Budget fit.
    within_budget: bool | None = None
    if profile.budget_aed is not None:
        within_budget = profile.budget_aed >= cost.first_year_total_aed[0]
        if within_budget:
            score += _BUDGET_FIT_BONUS
            reasons.append(
                Reason(
                    text=(
                        f"Fits your ~AED {profile.budget_aed:,} budget: estimated first-year "
                        f"cost from AED {cost.first_year_total_aed[0]:,}."
                    ),
                    citation=cost.citation,  # cost band citation
                )
            )
        else:
            score -= _BUDGET_OVER_PENALTY
            reasons.append(
                Reason(
                    text=(
                        f"Likely over your ~AED {profile.budget_aed:,} budget: estimated "
                        f"first-year cost starts around AED {cost.first_year_total_aed[0]:,}."
                    ),
                    citation=cost.citation,
                )
            )

    # Emirate preference (soft).
    if (
        profile.preferred_emirate
        and zone.get("emirate", "").lower() == profile.preferred_emirate.lower()
    ):
        score += _EMIRATE_PREFERENCE_BONUS
        reasons.append(
            Reason(
                text=f"Located in your preferred emirate ({zone['emirate']}).",
                citation=_zone_citation("emirate_preference", zone),
            )
        )

    return score, reasons, len(overlap)


def _rank_zones(
    profile: BusinessProfile, activity: dict[str, Any]
) -> list[ZoneRecommendation]:
    scored: list[tuple[float, int, ZoneRecommendation]] = []

    for zone in load_free_zones():
        cost = _cost_breakdown(profile, zone)
        score, match_reasons, overlap = _score_zone(profile, activity, zone, cost)

        # Only surface zones with at least one specialization match — a zone with
        # zero relevance should never appear in a shortlist.
        if overlap == 0:
            continue

        visa = _assess_visas(profile, zone)
        within_budget = (
            None
            if profile.budget_aed is None
            else profile.budget_aed >= cost.first_year_total_aed[0]
        )

        rec = ZoneRecommendation(
            zone_id=zone["id"],
            name=zone["name"],
            emirate=zone["emirate"],
            score=round(score, 2),
            match_reasons=match_reasons,
            cost=cost,
            visa=visa,
            within_budget=within_budget,
            pros=list(zone.get("pros", [])),
            cons=list(zone.get("cons", [])),
            url=zone.get("url", ""),
        )
        # Sort key: score desc, then overlap desc, then cheaper first-year cost.
        scored.append((score, overlap, rec))

    scored.sort(key=lambda t: (t[0], t[1], -t[2].cost.first_year_total_aed[0]), reverse=True)

    # Return top 3-5.
    top = [rec for _, _, rec in scored[:5]]
    return top


# --------------------------------------------------------------------------- #
# Public entry point
# --------------------------------------------------------------------------- #
def evaluate(profile: BusinessProfile) -> EligibilityResult:
    """Run the full deterministic evaluation for a business profile."""
    activity = get_activity(profile.activity_id)

    setup_type, setup_reasons = _decide_setup_type(profile, activity)
    ownership = _ownership_reasons(setup_type, profile)

    shortlist: list[ZoneRecommendation] = []
    if setup_type == SetupType.FREE_ZONE:
        shortlist = _rank_zones(profile, activity)

    # Collect a flat, de-duplicated citation trace for auditing.
    citations: list[Citation] = []
    seen: set[tuple[str, str]] = set()

    def _collect(cit: Citation | None) -> None:
        if cit is None:
            return
        key = (cit.rule_id, cit.source_ref)
        if key not in seen:
            seen.add(key)
            citations.append(cit)

    for r in setup_reasons + ownership:
        _collect(r.citation)
    for rec in shortlist:
        for r in rec.match_reasons:
            _collect(r.citation)
        _collect(rec.cost.citation)
        _collect(rec.visa.citation)

    disclaimers = list(STANDARD_DISCLAIMERS)
    if setup_type == SetupType.MAINLAND:
        disclaimers.append(
            "Mainland licensing is handled by the emirate's Department of Economy "
            "(DED); this MVP does not yet rank mainland options."
        )
    if activity.get("regulated"):
        disclaimers.append(
            f"“{activity['label']}” is a regulated activity — a sector regulator must "
            "license it in addition to the trade licence."
        )

    return EligibilityResult(
        activity_id=activity["id"],
        activity_label=activity["label"],
        setup_type=setup_type,
        setup_type_reasons=setup_reasons,
        ownership_reasons=ownership,
        zone_shortlist=shortlist,
        disclaimers=disclaimers,
        citations=citations,
    )
